"""Harvest real first-turn user prompts from WildChat-1M.

Why this exists: every accuracy number so far is measured on prompts that were
either hand-authored for the eval or generated by an LLM. Both are in-distribution
with our own idea of the task. Real traffic is the only set that can falsify
"high 90s". WildChat-1M is ungated real ChatGPT traffic.

Streamed, so we never materialise the full dataset. Filters: English, first user
turn, 15-2000 chars, deduped case-folded, and dropped if it looks like a raw
paste with no request in it.
"""
import json, re, hashlib, pathlib, sys, os
from datasets import load_dataset

OUT = pathlib.Path("/Users/cnuland/llm-d-sc-accuracy/data/eval/wildchat_pool.jsonl")
# The stream is deterministic, so re-harvesting a larger TARGET reproduces the
# original prefix byte-for-byte and appends only genuinely new prompts. That
# keeps every existing eval/train split valid while extending the pool.
TARGET = int(sys.argv[1]) if len(sys.argv) > 1 else 24000

seen, kept = set(), 0
ds = load_dataset("allenai/WildChat-1M", split="train", streaming=True,
                  token=os.environ.get("HF_TOKEN"))
with open(OUT, "w") as fh:
    for i, row in enumerate(ds):
        if kept >= TARGET:
            break
        if row.get("language") != "English" or row.get("toxic"):
            continue
        conv = row.get("conversation") or []
        if not conv or conv[0].get("role") != "user":
            continue
        t = (conv[0].get("content") or "").strip()
        if not (15 <= len(t) <= 2000):
            continue
        if t.count("\n") > 40:                      # raw dumps, not requests
            continue
        if not re.search(r"[A-Za-z]{3}", t):
            continue
        k = hashlib.blake2b(re.sub(r"\s+", " ", t.lower()).encode(), digest_size=12).hexdigest()
        if k in seen:
            continue
        seen.add(k)
        fh.write(json.dumps({"text": t, "src": "wildchat", "turns": len(conv)}) + "\n")
        kept += 1
        if kept % 2000 == 0:
            print(f"  kept {kept} (scanned {i})", flush=True)
print(f"DONE kept={kept} -> {OUT}")
